# Generated by Django 2.2 on 2020-09-12 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(upload_to='')),
                ('gif', models.FileField(blank=True, null=True, upload_to='')),
                ('video', models.CharField(blank=True, max_length=250, null=True)),
                ('creators', models.TextField(blank=True, null=True)),
                ('equipment', models.CharField(choices=[('Rings', 'Rings'), ('Bar', 'Bar'), ('Floor', 'Floor')], max_length=50)),
                ('primary_muscle', models.CharField(choices=[('Back', 'Back'), ('Chest', 'Chest'), ('Shoulder', 'Shoulder'), ('Bicep', 'Bicep'), ('Tricep', 'Tricep'), ('Legs', 'Legs'), ('Abs', 'Abs')], max_length=50)),
                ('secondary_muscle', models.CharField(blank=True, choices=[('Back', 'Back'), ('Chest', 'Chest'), ('Shoulder', 'Shoulder'), ('Bicep', 'Bicep'), ('Tricep', 'Tricep'), ('Legs', 'Legs'), ('Abs', 'Abs')], max_length=50, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('title', models.CharField(max_length=250)),
                ('body_weight', models.FloatField(blank=True, null=True)),
                ('energy_level', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='general.Exercise')),
            ],
            options={
                'ordering': ('num',),
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='general.Workout'),
        ),
    ]
