# Generated by Django 2.2 on 2020-09-25 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(default='rings_default.jpg', upload_to='')),
                ('gif', models.FileField(blank=True, null=True, upload_to='')),
                ('video', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(choices=[('Push', 'Push'), ('Pull', 'Pull'), ('Legs', 'Legs'), ('Core', 'Core'), ('Other', 'Other')], max_length=50)),
                ('muscle_category', models.CharField(choices=[('Back/Biceps', 'Back/Biceps'), ('Chest/Triceps', 'Chest/Triceps'), ('Shoulders', 'Shoulders'), ('Legs', 'Legs'), ('Core', 'Core'), ('Full Body', 'Full Body'), ('Other', 'Other')], default='Other', max_length=50)),
                ('type', models.CharField(blank=True, choices=[('Compound', 'Compound'), ('Isolated', 'Isolated'), ('Warmup', 'Warmup')], max_length=50, null=True)),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('equipments', models.ManyToManyField(blank=True, to='general.Equipment')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('website_url', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube_url', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('title', models.CharField(max_length=250)),
                ('body_weight', models.FloatField(blank=True, null=True)),
                ('energy_level', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('exercises', models.ManyToManyField(blank=True, to='general.Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('datetime',),
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('num', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='general.Exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='general.Workout')),
            ],
            options={
                'ordering': ('num',),
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.Trainer'),
        ),
    ]
