# Generated by Django 2.2 on 2020-09-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='set',
            name='num',
        ),
        migrations.AlterField(
            model_name='set',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
