# Generated by Django 2.2 on 2020-09-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='video',
            new_name='instruction_video',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='gif',
            new_name='short_demo',
        ),
    ]
