# Generated by Django 2.2 on 2020-09-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20200925_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
