# Generated by Django 2.2 on 2020-09-15 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200915_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='user',
        ),
        migrations.AddField(
            model_name='set',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='general.Workout'),
            preserve_default=False,
        ),
    ]
