# Generated by Django 2.2 on 2020-10-02 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20201002_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_category',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(blank=True, choices=[('Compound', 'Compound'), ('Corrective', 'Corrective'), ('Warmup', 'Warmup')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_target',
            field=models.ManyToManyField(blank=True, to='general.Muscle'),
        ),
    ]
