# Generated by Django 2.2 on 2020-09-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20200915_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.FileField(default='rings_default.jpg', upload_to=''),
        ),
    ]
