# Generated by Django 2.2 on 2020-10-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20201002_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty_level',
            field=models.PositiveIntegerField(),
        ),
    ]
