# Generated by Django 2.2 on 2020-09-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20200917_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ('num',)},
        ),
        migrations.AddField(
            model_name='set',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
