# Generated by Django 2.2 on 2020-11-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20201002_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercise_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
